name: master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker_release:
    uses: spuxx1701/ci-cd/.github/workflows/docker_release.yml@v2.0
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}

  helm_test:
    uses: spuxx1701/ci-cd/.github/workflows/helm_test.yml@v2.0

  helm_release:
    permissions:
      contents: write
    # needs:
    #   - helm_test
    uses: spuxx1701/ci-cd/.github/workflows/helm_release.yml@v2.0
    secrets:
      token: ${{ secrets.CR_TOKEN }}
