name: master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker_release:
    uses: spuxx1701/ci-cd/.github/workflows/release_image.yml@v2.0
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
