name: master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker_release:
    uses: spuxx1701/ci-cd/.github/workflows/docker_release.yml@v2.0
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}

  helm_release:
    permissions:
      contents: write
    needs:
      - docker_release
    uses: spuxx1701/ci-cd/.github/workflows/helm_release.yml@v2.0
    secrets:
      token: ${{ secrets.CR_TOKEN }}
